// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwxYi2f_PuLfYzE_g0h_Zy18OfTZ9NW3o',
    appId: '1:286425702636:web:fb2544919fa36956d685c9',
    messagingSenderId: '286425702636',
    projectId: 'cinema-booking-app-7df82',
    authDomain: 'cinema-booking-app-7df82.firebaseapp.com',
    storageBucket: 'cinema-booking-app-7df82.appspot.com',
    measurementId: 'G-T563MM8KV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU75QkwYWAwywHM4mVJBu1S_WyRd6cQxI',
    appId: '1:286425702636:android:b9d1ec48235668bcd685c9',
    messagingSenderId: '286425702636',
    projectId: 'cinema-booking-app-7df82',
    storageBucket: 'cinema-booking-app-7df82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk5eQG7p_UGWuPFygHmP5ardGimqebIb4',
    appId: '1:286425702636:ios:5df86d0b45f39991d685c9',
    messagingSenderId: '286425702636',
    projectId: 'cinema-booking-app-7df82',
    storageBucket: 'cinema-booking-app-7df82.appspot.com',
    iosBundleId: 'com.example.cinemaBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk5eQG7p_UGWuPFygHmP5ardGimqebIb4',
    appId: '1:286425702636:ios:5b7c43640a9eb0bed685c9',
    messagingSenderId: '286425702636',
    projectId: 'cinema-booking-app-7df82',
    storageBucket: 'cinema-booking-app-7df82.appspot.com',
    iosBundleId: 'com.example.cinemaBookingApp.RunnerTests',
  );
}
